server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrxindong/spring-in-action/
          searchPaths: licensingservice,organizationservice
          username: mrxindong
          password: w121775

