#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/mrxindong/config-repo/
#          searchPaths: licensingservice,organizationservice
#          username: mrxindong
#          password: w121775


server:
   port: 8080
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
#              searchLocations: /Users/mrxindong/Downloads/spring-in-action/confsvr/src/main/resources/resources/config/licensingservice
               searchLocations: classpath:resources/config/organizationservice,classpath:resources/config/licensingservice
